### ISSUE TITLE
Yesterdays update breaks site after composer update

### ISSUE THREAD

**Issue by HashandSalt** [beebmx/kirby-blade#1]
After updating yesterday, via composer, the Blade plugin causes this warning:

```
Warning: require_once(public/site/plugins/kirby-blade/vendor/autoload.php): failed to open stream: No such file or directory in /public/site/plugins/kirby-blade/index.php on line 3

Fatal error: require_once(): Failed opening required 'public/site/plugins/kirby-blade/vendor/autoload.php' (include_path='.:/usr/local/Cellar/valet-php@7.2/7.2.13/share/valet-php@7.2/pear') in public/site/plugins/kirby-blade/index.php on line 3
```

I think the Kirby composer installer also got updated yesterday.

I have the following installed...

```
        "php": ">=7.1.0",
        "getkirby/cms": "3.0.1",
        "omz13/kirby3-suncyclepages": "^1.0",
        "timoetting/kirby-builder": "^2.0",
        "sylvainjule/locator": "^1.0",
        "mzur/kirby-uniform": "^4.0",
        "flokosiol/focus": "^3.0",
        "sylvainjule/autofocus": "^1.0",
        "bnomei/kirby3-autoid": "^1.2",
        "bnomei/kirby3-mobile-detect": "^1.2",
        "bnomei/kirby3-srcset": "^1.2",
        "bnomei/kirby3-fingerprint": "^2.2",
        "k-community/markdown-field": "^1.0",
        "bnomei/kirby3-robots-txt": "^1.1",
        "omz13/kirby3-xmlsitemap": "@dev",
        "beebmx/kirby-blade": "^1.0",
        "sylvainjule/imageboxes": "^1.0",
        "sylvainjule/imageradio": "^1.0",
        "dg/twitter-php": "^3.7"
```

**Comment by lukasbestle** [comment]
See https://forum.getkirby.com/t/composer-issues/12866/2?u=lukasbestle for more information on how to fix this.

**Comment by beebmx** [comment]
The issue was fixed in 1.0.2

**Comment by HashandSalt** [comment]
Actually there is still a problem. I updated to 1.0.2 and I get a Kirby whoops with the following:

```
Whoops \ Exception \ ErrorException (E_ERROR)
Class 'Jenssegers\Blade\Blade' not found 
```

**Comment by beebmx** [comment]
It's now fixed in 1.0.5
